.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - build
  - test

before_script:
  - powershell Install-WindowsFeature Net-Framework-Core

build:
  extends: .shared_windows_runners
  stage: build
  script:
    - cd passbolt
    - msbuild /t:Build /p:Configuration=Release

test:
  extends: .shared_windows_runners
  stage: test
  script:
    - cd passbolt-windows-tests
    - msbuild /t:Build /p:Configuration=Release
    - cd bin/Release
    - vstest.console.exe uwp-application-tests.dll
