.shared_windows_runners:
  tags: 
    - shared-windows
    - windows
    - windows-1809

stages:
  - build
  - test

before_script:
  - powershell Install-WindowsFeature Net-Framework-Core

build:
  extends: .shared_windows_runners
  stage: build
  script:
    - cd passbolt
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\"
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" "passbolt-windows.sln /t:Build /p:Configuration=Release /m"'

test:
  extends: .shared_windows_runners
  stage: test
  script:
    - cd passbolt-windows-tests
    - msbuild /t:Build /p:Configuration=Release
    - cd bin/Release
    - vstest.console.exe uwp-application-tests.dll

linter:
  stage: test
  image: node:16
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
  script:
    - cd passbolt/Webviews/Background/
    - npm install
    - npm run eslint

npm-dependencies-check:
  stage: test
  image: node:16
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
  script:
    - cd passbolt/Webviews/Background/
    - npm outdated

dotnet- dependencies-check:
  extends: .shared_windows_runners
  stage: test
  script:
    - dotnet tool install --global dotnet-outdated-tool
    - dotnet outdated
