image: mcr.microsoft.com/windows:1809

stages:
  - build
  - test

before_script:
  - powershell Install-WindowsFeature Net-Framework-Core

build:
  stage: build
  script:
    - cd uwp-application
    - msbuild /t:Build /p:Configuration=Release

test:
  stage: test
  script:
    - cd uwp-application-tests
    - msbuild /t:Build /p:Configuration=Release
    - cd bin/Release
    - vstest.console.exe uwp-application-tests.dll
